version: 2.1

orbs:
  plantuml: orbss/plantuml@0.4.40

workflows:
  version: 2
  generator:
    jobs:
      - plantuml/generate-svg:
          extension: ".uml"
          workspace_root: /tmp/circleci_workspace
          workspace_path: .
